### ISSUE TITLE
[STORY] Main Page

### ISSUE THREAD

**Issue by larskii12** [larskii12/mobile-computing#20]
Epic: #2 

### Description
As a user, I want the app to display all study locations and coffee places in the main page so that I can easily navigate the locations around the application.

### Tasks
- [] Task 1: Location Cards
- [] Task 2: Information Icons
- [] Task 3: Navigation Bar
