### ISSUE TITLE
[STORY] Database

### ISSUE THREAD

**Issue by larskii12** [larskii12/mobile-computing#22]
Epic: #21 

### Description
As a user, I want to have a database that stores information on everything in the application so that it can make the app smarter.

### Tasks
- [] Task 1: Setting Up Database
- [] Task 2: Connect Database to Application
- [] Task 3: CRUD from App to Database
