### ISSUE TITLE
[STORY] Log-in Page

### ISSUE THREAD

**Issue by larskii12** [larskii12/mobile-computing#23]
Epic: #19 

### Description
As a user, I want the option to log in using either my email address or username so that I can choose whichever convenient and less effort to type.

### Tasks
- [] Task 1: Log-in Page UI
- [] Task 2: Logging in by Email
- [] Task 3: Logging in by Username
- [] Task 4: Forget Password
- [] Task 5: Failed to Login
